[package]
name = "bluetooth_server"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.5"  # 用於藍牙通信
tokio = { version = "1", features = ["full"] }  # 異步運行時
futures = "0.3"
log = "0.4"
pretty_env_logger = "0.4"